-- StayEase / AI Hotel Booking Platform - Complete Supabase Setup
-- Run this file in Supabase Dashboard -> SQL Editor -> New query.
--
-- What this sets up:
-- 1. Auth profile table linked to auth.users
-- 2. Auto profile creation on user signup
-- 3. Hotels table compatible with both:
--    - requested dataset fields: hotel_name, address, latitude, longitude, price_per_night, image_url
--    - existing app fields: name, slug, location, price_from, images
-- 4. Rooms, bookings, reviews, wishlist, contact messages
-- 5. Indexes, triggers, RLS policies, and role helpers
--
-- Important:
-- Supabase Auth itself is built into every Supabase project. SQL can create
-- profile triggers and database policies, but email provider / OTP / redirect
-- URL settings must be configured from the Supabase Dashboard.

BEGIN;

-- ============================================================
-- EXTENSIONS
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- HELPERS
-- ============================================================
CREATE OR REPLACE FUNCTION public.slugify(value TEXT)
RETURNS TEXT AS $$
  SELECT trim(BOTH '-' FROM regexp_replace(lower(coalesce(value, '')), '[^a-z0-9]+', '-', 'g'));
$$ LANGUAGE sql IMMUTABLE;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- PROFILES - EXTENDS SUPABASE AUTH USERS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'owner', 'admin')),
  avatar_url TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  requested_role TEXT;
BEGIN
  requested_role := COALESCE(NEW.raw_user_meta_data->>'role', 'user');

  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    NEW.id,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'name', ''), split_part(NEW.email, '@', 1), 'User'),
    NEW.email,
    CASE
      WHEN requested_role = 'owner' THEN 'owner'
      ELSE 'user'
    END
  )
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    updated_at = NOW();

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

DROP TRIGGER IF EXISTS profiles_updated_at ON public.profiles;
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.current_user_role()
RETURNS TEXT AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
  SELECT COALESCE(public.current_user_role() = 'admin', false);
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;

-- ============================================================
-- HOTELS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.hotels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100001) PRIMARY KEY,
  owner_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,

  -- Requested structure
  hotel_name TEXT,
  city TEXT NOT NULL,
  state TEXT,
  address TEXT,
  latitude NUMERIC(9,6) CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  longitude NUMERIC(9,6) CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  star_rating NUMERIC(2,1) CHECK (star_rating IS NULL OR star_rating BETWEEN 1 AND 5),
  review_score NUMERIC(2,1) DEFAULT 0 CHECK (review_score BETWEEN 0 AND 5),
  review_count INTEGER DEFAULT 0 CHECK (review_count >= 0),
  price_per_night INTEGER DEFAULT 0 CHECK (price_per_night >= 0),
  category TEXT CHECK (category IS NULL OR category IN ('Budget', 'Standard', 'Premium', 'Luxury')),
  amenities TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  description TEXT,
  image_url TEXT,
  phone TEXT,
  email TEXT,

  -- Existing React app compatibility fields
  name TEXT,
  slug TEXT UNIQUE,
  location TEXT,
  country TEXT NOT NULL DEFAULT 'India',
  images TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  rating NUMERIC(3,2) DEFAULT 0 CHECK (rating BETWEEN 0 AND 5),
  price_from INTEGER DEFAULT 0 CHECK (price_from >= 0),
  is_verified BOOLEAN NOT NULL DEFAULT false,
  is_featured BOOLEAN NOT NULL DEFAULT false,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT hotels_has_name CHECK (hotel_name IS NOT NULL OR name IS NOT NULL),
  CONSTRAINT hotels_has_location CHECK (address IS NOT NULL OR location IS NOT NULL)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'hotels_hotel_name_key'
      AND conrelid = 'public.hotels'::regclass
  ) THEN
    ALTER TABLE public.hotels
      ADD CONSTRAINT hotels_hotel_name_key UNIQUE (hotel_name);
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.set_hotel_defaults()
RETURNS TRIGGER AS $$
BEGIN
  NEW.hotel_name := COALESCE(NULLIF(NEW.hotel_name, ''), NULLIF(NEW.name, ''));
  NEW.name := COALESCE(NULLIF(NEW.name, ''), NEW.hotel_name);

  NEW.address := COALESCE(NULLIF(NEW.address, ''), NULLIF(NEW.location, ''));
  NEW.location := COALESCE(NULLIF(NEW.location, ''), NEW.address);

  NEW.price_per_night := COALESCE(NULLIF(NEW.price_per_night, 0), NEW.price_from, 0);
  NEW.price_from := COALESCE(NULLIF(NEW.price_from, 0), NEW.price_per_night, 0);

  IF (NEW.image_url IS NULL OR NEW.image_url = '') AND cardinality(NEW.images) > 0 THEN
    NEW.image_url := NEW.images[1];
  END IF;

  IF (NEW.images IS NULL OR cardinality(NEW.images) = 0) AND NEW.image_url IS NOT NULL THEN
    NEW.images := ARRAY[NEW.image_url];
  END IF;

  NEW.rating := COALESCE(NULLIF(NEW.rating, 0), NEW.review_score, 0);

  IF NEW.slug IS NULL OR NEW.slug = '' THEN
    NEW.slug := public.slugify(
      NEW.hotel_name || '-' || COALESCE(NEW.id::TEXT, substr(gen_random_uuid()::TEXT, 1, 8))
    );
  ELSE
    NEW.slug := public.slugify(NEW.slug);
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS hotels_set_defaults ON public.hotels;
CREATE TRIGGER hotels_set_defaults
  BEFORE INSERT OR UPDATE ON public.hotels
  FOR EACH ROW EXECUTE FUNCTION public.set_hotel_defaults();

DROP TRIGGER IF EXISTS hotels_updated_at ON public.hotels;
CREATE TRIGGER hotels_updated_at
  BEFORE UPDATE ON public.hotels
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX IF NOT EXISTS idx_hotels_city ON public.hotels(city);
CREATE INDEX IF NOT EXISTS idx_hotels_state ON public.hotels(state);
CREATE INDEX IF NOT EXISTS idx_hotels_slug ON public.hotels(slug);
CREATE INDEX IF NOT EXISTS idx_hotels_location ON public.hotels(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_hotels_price ON public.hotels(price_per_night);
CREATE INDEX IF NOT EXISTS idx_hotels_category ON public.hotels(category);
CREATE INDEX IF NOT EXISTS idx_hotels_featured ON public.hotels(is_featured) WHERE is_featured = true;
CREATE INDEX IF NOT EXISTS idx_hotels_amenities ON public.hotels USING GIN (amenities);

CREATE OR REPLACE FUNCTION public.owns_hotel(target_hotel_id INTEGER)
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.hotels
    WHERE id = target_hotel_id
      AND owner_id = auth.uid()
  );
$$ LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public;

-- ============================================================
-- ROOMS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.rooms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hotel_id INTEGER NOT NULL REFERENCES public.hotels(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  description TEXT,
  price INTEGER NOT NULL CHECK (price > 0),
  capacity INTEGER NOT NULL DEFAULT 2 CHECK (capacity > 0),
  available BOOLEAN NOT NULL DEFAULT true,
  images TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rooms_hotel ON public.rooms(hotel_id);
CREATE INDEX IF NOT EXISTS idx_rooms_available ON public.rooms(available);

DROP TRIGGER IF EXISTS rooms_updated_at ON public.rooms;
CREATE TRIGGER rooms_updated_at
  BEFORE UPDATE ON public.rooms
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- BOOKINGS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  hotel_id INTEGER NOT NULL REFERENCES public.hotels(id) ON DELETE CASCADE,
  room_id UUID REFERENCES public.rooms(id) ON DELETE SET NULL,
  check_in DATE NOT NULL,
  check_out DATE NOT NULL,
  guests INTEGER NOT NULL DEFAULT 1 CHECK (guests > 0),
  amount INTEGER NOT NULL CHECK (amount >= 0),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT bookings_valid_dates CHECK (check_out > check_in)
);

CREATE INDEX IF NOT EXISTS idx_bookings_user ON public.bookings(user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_hotel ON public.bookings(hotel_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON public.bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_dates ON public.bookings(check_in, check_out);

DROP TRIGGER IF EXISTS bookings_updated_at ON public.bookings;
CREATE TRIGGER bookings_updated_at
  BEFORE UPDATE ON public.bookings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- REVIEWS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  hotel_id INTEGER NOT NULL REFERENCES public.hotels(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, hotel_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_hotel ON public.reviews(hotel_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON public.reviews(user_id);

DROP TRIGGER IF EXISTS reviews_updated_at ON public.reviews;
CREATE TRIGGER reviews_updated_at
  BEFORE UPDATE ON public.reviews
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- WISHLIST
-- ============================================================
CREATE TABLE IF NOT EXISTS public.wishlist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  hotel_id INTEGER NOT NULL REFERENCES public.hotels(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, hotel_id)
);

CREATE INDEX IF NOT EXISTS idx_wishlist_user ON public.wishlist(user_id);
CREATE INDEX IF NOT EXISTS idx_wishlist_hotel ON public.wishlist(hotel_id);

-- ============================================================
-- CONTACT MESSAGES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_contact_messages_read ON public.contact_messages(is_read);
CREATE INDEX IF NOT EXISTS idx_contact_messages_created ON public.contact_messages(created_at DESC);

-- ============================================================
-- GRANTS
-- ============================================================
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public.hotels, public.rooms, public.reviews TO anon, authenticated;
GRANT ALL ON public.profiles, public.hotels, public.rooms, public.bookings, public.reviews, public.wishlist, public.contact_messages TO authenticated;
GRANT INSERT ON public.contact_messages TO anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hotels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- PROFILES POLICIES
DROP POLICY IF EXISTS "Profiles are viewable by authenticated users" ON public.profiles;
CREATE POLICY "Profiles are viewable by authenticated users"
  ON public.profiles FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id AND role = public.current_user_role());

DROP POLICY IF EXISTS "Admins can manage profiles" ON public.profiles;
CREATE POLICY "Admins can manage profiles"
  ON public.profiles FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- HOTELS POLICIES
DROP POLICY IF EXISTS "Hotels are publicly readable" ON public.hotels;
CREATE POLICY "Hotels are publicly readable"
  ON public.hotels FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "Owners can create hotels" ON public.hotels;
CREATE POLICY "Owners can create hotels"
  ON public.hotels FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin() OR owner_id = auth.uid());

DROP POLICY IF EXISTS "Owners can update own hotels" ON public.hotels;
CREATE POLICY "Owners can update own hotels"
  ON public.hotels FOR UPDATE
  TO authenticated
  USING (public.is_admin() OR owner_id = auth.uid())
  WITH CHECK (public.is_admin() OR owner_id = auth.uid());

DROP POLICY IF EXISTS "Owners can delete own hotels" ON public.hotels;
CREATE POLICY "Owners can delete own hotels"
  ON public.hotels FOR DELETE
  TO authenticated
  USING (public.is_admin() OR owner_id = auth.uid());

-- ROOMS POLICIES
DROP POLICY IF EXISTS "Rooms are publicly readable" ON public.rooms;
CREATE POLICY "Rooms are publicly readable"
  ON public.rooms FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "Hotel owners can create rooms" ON public.rooms;
CREATE POLICY "Hotel owners can create rooms"
  ON public.rooms FOR INSERT
  TO authenticated
  WITH CHECK (public.is_admin() OR public.owns_hotel(hotel_id));

DROP POLICY IF EXISTS "Hotel owners can update rooms" ON public.rooms;
CREATE POLICY "Hotel owners can update rooms"
  ON public.rooms FOR UPDATE
  TO authenticated
  USING (public.is_admin() OR public.owns_hotel(hotel_id))
  WITH CHECK (public.is_admin() OR public.owns_hotel(hotel_id));

DROP POLICY IF EXISTS "Hotel owners can delete rooms" ON public.rooms;
CREATE POLICY "Hotel owners can delete rooms"
  ON public.rooms FOR DELETE
  TO authenticated
  USING (public.is_admin() OR public.owns_hotel(hotel_id));

-- BOOKINGS POLICIES
DROP POLICY IF EXISTS "Users and hotel owners can view bookings" ON public.bookings;
CREATE POLICY "Users and hotel owners can view bookings"
  ON public.bookings FOR SELECT
  TO authenticated
  USING (public.is_admin() OR auth.uid() = user_id OR public.owns_hotel(hotel_id));

DROP POLICY IF EXISTS "Users can create own bookings" ON public.bookings;
CREATE POLICY "Users can create own bookings"
  ON public.bookings FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users and hotel owners can update bookings" ON public.bookings;
CREATE POLICY "Users and hotel owners can update bookings"
  ON public.bookings FOR UPDATE
  TO authenticated
  USING (public.is_admin() OR auth.uid() = user_id OR public.owns_hotel(hotel_id))
  WITH CHECK (public.is_admin() OR auth.uid() = user_id OR public.owns_hotel(hotel_id));

DROP POLICY IF EXISTS "Admins can delete bookings" ON public.bookings;
CREATE POLICY "Admins can delete bookings"
  ON public.bookings FOR DELETE
  TO authenticated
  USING (public.is_admin());

-- REVIEWS POLICIES
DROP POLICY IF EXISTS "Reviews are publicly readable" ON public.reviews;
CREATE POLICY "Reviews are publicly readable"
  ON public.reviews FOR SELECT
  TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "Users can create own reviews" ON public.reviews;
CREATE POLICY "Users can create own reviews"
  ON public.reviews FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own reviews" ON public.reviews;
CREATE POLICY "Users can update own reviews"
  ON public.reviews FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id OR public.is_admin())
  WITH CHECK (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Users can delete own reviews" ON public.reviews;
CREATE POLICY "Users can delete own reviews"
  ON public.reviews FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id OR public.is_admin());

-- WISHLIST POLICIES
DROP POLICY IF EXISTS "Users can view own wishlist" ON public.wishlist;
CREATE POLICY "Users can view own wishlist"
  ON public.wishlist FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can create own wishlist" ON public.wishlist;
CREATE POLICY "Users can create own wishlist"
  ON public.wishlist FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own wishlist" ON public.wishlist;
CREATE POLICY "Users can delete own wishlist"
  ON public.wishlist FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

-- CONTACT MESSAGES POLICIES
DROP POLICY IF EXISTS "Anyone can submit contact messages" ON public.contact_messages;
CREATE POLICY "Anyone can submit contact messages"
  ON public.contact_messages FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can view contact messages" ON public.contact_messages;
CREATE POLICY "Admins can view contact messages"
  ON public.contact_messages FOR SELECT
  TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can update contact messages" ON public.contact_messages;
CREATE POLICY "Admins can update contact messages"
  ON public.contact_messages FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Admins can delete contact messages" ON public.contact_messages;
CREATE POLICY "Admins can delete contact messages"
  ON public.contact_messages FOR DELETE
  TO authenticated
  USING (public.is_admin());

COMMIT;

-- ============================================================
-- OPTIONAL ADMIN SETUP
-- ============================================================
-- 1. Sign up once from your app using the email that should become admin.
-- 2. Then run this manually in SQL Editor:
--
-- UPDATE public.profiles
-- SET role = 'admin'
-- WHERE email = 'your-admin-email@example.com';
--
-- ============================================================
-- OPTIONAL 5000 HOTELS IMPORT
-- ============================================================
-- Do not paste data/hotels.sql if the SQL Editor rejects large queries.
-- Use the smaller files in supabase/hotel_import instead:
--   1. Optional: supabase/hotel_import/00_clear_hotels.sql
--   2. supabase/hotel_import/part_01.sql through part_10.sql
-- Or run npm run seed:postgres:hotels with DATABASE_URL/POSTGRES_URL set.
